name: workshop-ci

on:
  # run on pull request events for the master branch only
  pull_request:
    branches: [ master ]
    paths-ignore:
    - LICENSE
    - '**.md'
    - .github/workflows/run-crucible-tracking.yaml
    - .github/workflows/faux-crucible-ci.yaml
    - .github/workflows/faux-workshop-ci.yaml
    - 'docs/**'

  # allow for manual invocation from the actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}/workshop-ci
  cancel-in-progress: true

jobs:
  workshop-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Perl Dependencies
      run: |
        sudo apt install libcoro-perl libjson-perl libjson-xs-perl libjson-validator-perl libdata-uuid-perl libdigest-sha-perl libcompress-raw-lzma-perl libcompress-raw-zlib-perl libcompress-raw-bzip2-perl cpanminus
        echo
        sudo cpanm IO::Uncompress::UnXz IO::Compress::Xz

    - name: Install Toolbox
      run: |
        pushd ~/
        git clone https://github.com/perftool-incubator/toolbox.git

    - name: Run workshop - dump-config
      run: |
        export TOOLBOX_HOME=~/toolbox
        echo
        sudo --preserve-env=TOOLBOX_HOME ./workshop.pl --log-level verbose --label workshop-ci-dump-config --userenv ./userenvs/fedora-ci.json --dump-config true

    - name: Run workshop - dump-config - force-update-policy missing
      run: |
        export TOOLBOX_HOME=~/toolbox
        echo
        sudo --preserve-env=TOOLBOX_HOME ./workshop.pl --log-level verbose --label workshop-ci-dump-config --userenv ./userenvs/fedora-ci.json --dump-config true --force-update-policy missing

    - name: Run workshop - dump-files
      run: |
        export TOOLBOX_HOME=~/toolbox
        echo
        sudo --preserve-env=TOOLBOX_HOME ./workshop.pl --log-level verbose --label workshop-ci-dump-files --userenv ./userenvs/fedora-ci.json --dump-files true

    - name: Run workshop
      run: |
        export TOOLBOX_HOME=~/toolbox
        echo
        sudo --preserve-env=TOOLBOX_HOME ./workshop.pl --log-level verbose --label workshop-ci --userenv ./userenvs/fedora-ci.json
